# Generated by Django 3.0.3 on 2020-03-01 06:17

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=200)),
                ('email_body', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('send_to_committee', models.BooleanField(default=False)),
                ('send_to_all_members', models.BooleanField(default=False)),
                ('custom_recipients', models.BooleanField(default=False)),
                ('recipients_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
            ],
        ),
    ]
