# Generated by Django 3.0.3 on 2020-02-23 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=300)),
                ('detail', models.TextField(blank=True)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('posted_by', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('send_to_committee', models.BooleanField(default=False)),
                ('send_to_all_members', models.BooleanField(default=False)),
                ('picture1', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/')),
                ('picture2', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/')),
                ('picture3', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/')),
                ('picture4', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/')),
                ('picture5', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/')),
                ('picture6', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/')),
                ('picture7', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/')),
                ('picture8', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/')),
                ('picture9', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/')),
                ('picture10', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d/')),
            ],
        ),
    ]
