# Generated by Django 3.0.3 on 2020-02-23 10:08

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executive_committee_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('introduction', models.CharField(blank=True, max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='contact phone number', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_published', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, upload_to='photos/mayors/')),
            ],
        ),
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('introduction', models.CharField(blank=True, max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='contact phone number', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_published', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, upload_to='photos/mayors/')),
            ],
        ),
    ]
