# Generated by Django 3.0.3 on 2020-03-01 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman_name', models.CharField(max_length=200)),
                ('paragraph1', models.TextField(blank=True)),
                ('paragraph2', models.TextField(blank=True)),
                ('paragraph3', models.TextField(blank=True)),
                ('paragraph4', models.TextField(blank=True)),
                ('paragraph5', models.TextField(blank=True)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('chairman_picture', models.ImageField(blank=True, upload_to='photos/about/%Y/%m/%d/')),
            ],
        ),
    ]
