# Generated by Django 3.0.3 on 2020-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='chairman_signature',
            field=models.ImageField(blank=True, upload_to='photos/about/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='about',
            name='paragraph6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='paragraph7',
            field=models.TextField(blank=True),
        ),
    ]
