# Generated by Django 3.0.3 on 2020-03-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='send_to_all_members',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='send_to_committee',
        ),
    ]
